# This is a basic workflow to help you get started with Actions

name: Create Issue Task Clickup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  issues:
    types: ["opened"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # build:
  # The type of runner that the job will run on
  # runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
  # steps:
  #   - name: Get issue event fields
  #     run: echo ${{ github.event.issue }}
  #   - name: Get issue number
  #     run: echo ${{ github.event.issue.number }}
  #   - name: Get issue title
  #     run: echo ${{ github.event.issue.title }}
  #   - name: Get issue body
  #     run: echo ${{ github.event.issue.body }}

  create-product:
    runs-on: ubuntu-latest
    steps:
      - name: Create product
        id: create
        run: |
          PRODUCT=$(curl --location --request POST "https://dummyjson.com/products/add" \
          --header "Content-Type: application/json" \
          --data '{"title": "Test product"}')
          echo "PRODUCT=$PRODUCT" >> "$GITHUB_OUTPUT"
      - name: Grep product
        run: |
          PRODUCT_NAME=$(echo '${{ steps.create.outputs.PRODUCT }}' | grep -o '"title": *"[^"]*"' | grep -o '"[^"]*"$')
          echo $PRODUCT_NAME
      #   run: |
      #     PRODUCT_NAME=$(echo $PRODUCT | grep -o '"title": *"[^"]*"' | grep -o '"[^"]*"$')
      # - name: Show product name
      #   run: |
      #     echo $PRODUCT_NAME

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # # Runs a single command using the runners shell
      # - name: Create task on ClickUp
      #   run: |
      #     DATA='{"name":"Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}","description": "${{ github.event.issue.body }}"}'
      #     curl --location --request POST "https://api.clickup.com/api/v2/list/${{ secrets.CLICKUP_LIST_ID }}/task" \
      #       --header "Authorization: ${{ secrets.CLICKUP_TOKEN }}" \
      #       --header "Content-Type: application/json" \
      #       --data "$DATA"
      #       --fail
