name: Create Issue Task Clickup

on:
  issues:
    types: ["opened"]

jobs:
  main:
    name: Create Issue Task Clickup
    runs-on: ubuntu-latest
    environment: Integrations

    steps:
      - name: Create task on ClickUp
        id: create_task
        run: |
          DATA='{"name":"Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}","description": "${{ github.event.issue.body }}"}'
          TASK=$(curl --location --request POST "https://api.clickup.com/api/v2/list/${{ secrets.CLICKUP_LIST_ID }}/task" \
            --header "Authorization: ${{ secrets.CLICKUP_TOKEN }}" \
            --header "Content-Type: application/json" \
            --fail \
            --data "$DATA")
          echo "TASK=$TASK" >> "$GITHUB_OUTPUT"
      - name: Get task id
        id: get_task_id
        run: |
          TASK_ID=$(echo '${{ steps.create_task.outputs.TASK }}' | grep -o '"id": *"[^"]*"' | head -1 | grep -o '"[^"]*"$' | tr -d '"')
          echo "TASK_ID=$TASK_ID" >> "$GITHUB_OUTPUT"
      - name: Add issue url in the comments
        run: |
          DATA='{"comment_text":"Issue related: https://github.com/enovarsolutions/meutudo-ui/issues/${{ github.event.issue.number }}"}'
            curl --location --request POST "https://api.clickup.com/api/v2/task/${{ steps.get_task_id.outputs.TASK_ID }}/comment" \
              --header "Authorization: ${{ secrets.CLICKUP_TOKEN }}" \
              --header "Content-Type: application/json" \
              --data "$DATA"
