name: Create Issue task on ClickUp

on:
  issue:
    types:
      - opened

jobs:
  create-task:
    name: Create Issue task on ClickUp
    runs-on: ubuntu-latest
    steps:
      - name: Create task on ClickUp
        shell: bash
        run: |
          DATA='{"name":"Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}","description": "${{ github.event.issue.body }}"}'
          curl --location --request POST "https://api.clickup.com/api/v2/list/${{ secrets.CLICKUP_LIST_ID }}/task" \
            --header "Authorization: ${{ secrets.CLICKUP_TOKEN }}" \
            --header "Content-Type: application/json" \
            --data "$DATA"
